/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TyyEcVfkoA0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function HomePage1() {
  return (
    (<div className="flex min-h-screen flex-col bg-background">
      <header
        className="container mx-auto flex h-20 w-full max-w-7xl items-center justify-between px-4 md:px-6">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-bold">SopKit</span>
        </Link>
        <nav className="hidden space-x-4 md:flex">
          <Link
            href="#"
            className="text-muted-foreground hover:text-foreground"
            prefetch={false}>
            Tools
          </Link>
          <Link
            href="#"
            className="text-muted-foreground hover:text-foreground"
            prefetch={false}>
            Pricing
          </Link>
          <Link
            href="#"
            className="text-muted-foreground hover:text-foreground"
            prefetch={false}>
            About
          </Link>
          <Link
            href="#"
            className="text-muted-foreground hover:text-foreground"
            prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button variant="outline">Sign In</Button>
      </header>
      <main className="flex-1">
        <section
          className="container mx-auto flex h-[calc(100vh-theme(spacing.20))] max-w-7xl flex-col items-center justify-center px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
              Unlock the Power of JavaScript
            </h1>
            <p className="text-muted-foreground md:text-xl">
              Explore our suite of free online tools and utilities to streamline your JavaScript development workflow.
            </p>
          </div>
          <form className="mt-8 w-full max-w-3xl">
            <div className="relative">
              <SearchIcon
                className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Search tools and utilities..."
                className="w-full rounded-full border-2 border-input bg-background pl-12 pr-4 py-3 text-lg focus:border-primary focus:outline-none" />
            </div>
          </form>
        </section>
        <section className="container mx-auto my-12 max-w-7xl px-4 md:px-6">
          <div
            className="grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <Link
              href="#"
              className="group flex flex-col items-start rounded-lg border border-input bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
              prefetch={false}>
              <div
                className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <CodeIcon className="h-6 w-6" />
              </div>
              <h3 className="mt-4 text-lg font-medium">Code Formatter</h3>
              <p className="mt-2 text-muted-foreground">Beautify and format your JavaScript code.</p>
            </Link>
            <Link
              href="#"
              className="group flex flex-col items-start rounded-lg border border-input bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
              prefetch={false}>
              <div
                className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <PuzzleIcon className="h-6 w-6" />
              </div>
              <h3 className="mt-4 text-lg font-medium">Regex Tester</h3>
              <p className="mt-2 text-muted-foreground">Test and debug your regular expressions.</p>
            </Link>
            <Link
              href="#"
              className="group flex flex-col items-start rounded-lg border border-input bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
              prefetch={false}>
              <div
                className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <CpuIcon className="h-6 w-6" />
              </div>
              <h3 className="mt-4 text-lg font-medium">Performance Analyzer</h3>
              <p className="mt-2 text-muted-foreground">
                Analyze and optimize the performance of your JavaScript code.
              </p>
            </Link>
            <Link
              href="#"
              className="group flex flex-col items-start rounded-lg border border-input bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
              prefetch={false}>
              <div
                className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <BrushIcon className="h-6 w-6" />
              </div>
              <h3 className="mt-4 text-lg font-medium">Color Palette</h3>
              <p className="mt-2 text-muted-foreground">Explore and generate color palettes for your projects.</p>
            </Link>
          </div>
        </section>
      </main>
      <footer className="border-t">
        <div
          className="container mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-6">
          <p className="text-sm text-muted-foreground">&copy; 2024 SopKit. All rights reserved.</p>
          <div className="flex items-center space-x-4">
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}>
              Privacy
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}>
              Terms
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-foreground"
              prefetch={false}>
              Feedback
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function BrushIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9.06 11.9 8.07-8.06a2.85 2.85 0 1 1 4.03 4.03l-8.06 8.08" />
      <path
        d="M7.07 14.94c-1.66 0-3 1.35-3 3.02 0 1.33-2.5 1.52-2 2.02 1.08 1.1 2.49 2.02 4 2.02 2.2 0 4-1.8 4-4.04a3.01 3.01 0 0 0-3-3.02z" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function CpuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="16" height="16" x="4" y="4" rx="2" />
      <rect width="6" height="6" x="9" y="9" rx="1" />
      <path d="M15 2v2" />
      <path d="M15 20v2" />
      <path d="M2 15h2" />
      <path d="M2 9h2" />
      <path d="M20 15h2" />
      <path d="M20 9h2" />
      <path d="M9 2v2" />
      <path d="M9 20v2" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function PuzzleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19.439 7.85c-.049.322.059.648.289.878l1.568 1.568c.47.47.706 1.087.706 1.704s-.235 1.233-.706 1.704l-1.611 1.611a.98.98 0 0 1-.837.276c-.47-.07-.802-.48-.968-.925a2.501 2.501 0 1 0-3.214 3.214c.446.166.855.497.925.968a.979.979 0 0 1-.276.837l-1.61 1.61a2.404 2.404 0 0 1-1.705.707 2.402 2.402 0 0 1-1.704-.706l-1.568-1.568a1.026 1.026 0 0 0-.877-.29c-.493.074-.84.504-1.02.968a2.5 2.5 0 1 1-3.237-3.237c.464-.18.894-.527.967-1.02a1.026 1.026 0 0 0-.289-.877l-1.568-1.568A2.402 2.402 0 0 1 1.998 12c0-.617.236-1.234.706-1.704L4.23 8.77c.24-.24.581-.353.917-.303.515.077.877.528 1.073 1.01a2.5 2.5 0 1 0 3.259-3.259c-.482-.196-.933-.558-1.01-1.073-.05-.336.062-.676.303-.917l1.525-1.525A2.402 2.402 0 0 1 12 1.998c.617 0 1.234.236 1.704.706l1.568 1.568c.23.23.556.338.877.29.493-.074.84-.504 1.02-.968a2.5 2.5 0 1 1 3.237 3.237c-.464.18-.894.527-.967 1.02Z" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
