
"use client";
import { Check, Copy, Download, FileText, Filter, ListFilter, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

function parseCsv(text:string){
  const rows:string[][]=[]; let row:string[]=[], cell="", quoted=false;
  for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1]; if(ch==="\""&&quoted&&next==="\""){cell+="\"";i++;} else if(ch==="\"") quoted=!quoted; else if(ch===","&&!quoted){row.push(cell);cell="";} else if((ch==="\\n"||ch==="\\r")&&!quoted){if(ch==="\\r"&&next==="\\n")i++;row.push(cell);cell="";if(row.some(v=>v.trim()))rows.push(row);row=[];} else cell+=ch;}
  row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;
}
export default function CsvColumnExtractorTool(){
  const [input,setInput]=useState(""),[selected,setSelected]=useState<string[]>([]),[sort,setSort]=useState(false),[dedupe,setDedupe]=useState(true),[rows,setRows]=useState<Record<string,string>[]>([]);
  const table=useMemo(()=>parseCsv(input),[input]),headers=table[0]||[];
  const active=selected.length?selected:headers;
  const sample=()=>setInput("name,email,role,team\\nAda,ada@example.com,Engineer,Core\\nLinus,linus@example.com,Developer,Kernel\\nGrace,grace@example.com,Engineer,Research");
  const extract=()=>{if(table.length<2){toast.error("Add a header row and at least one data row.");return;}let out=table.slice(1).map((cells)=>Object.fromEntries(active.map((name)=>[name,cells[headers.indexOf(name)]??""])));if(dedupe){const seen=new Set<string>();out=out.filter((row)=>{const key=JSON.stringify(row);if(seen.has(key))return false;seen.add(key);return true;});}if(sort)out.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b),undefined,{numeric:true}));setRows(out);toast.success(out.length+" rows extracted");};
  const copy=async()=>{await navigator.clipboard.writeText(rows.map(r=>JSON.stringify(r)).join("\n"));toast.success("Copied");};
  const exportCsv=()=>{const esc=(v:string)=>"\""+v.replace(/"/g,"\"\"")+"\"";const content=[active.map(esc).join(","),...rows.map(r=>active.map(k=>esc(r[k]||"")).join(","))].join("\n");const href=URL.createObjectURL(new Blob([content],{type:"text/csv"}));const a=document.createElement("a");a.href=href;a.download="extracted-columns.csv";a.click();URL.revokeObjectURL(href);};
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><div className="rounded-xl border border-border/70 bg-muted/40 p-2.5"><ListFilter className="h-5 w-5"/></div><div><CardTitle className="text-lg">CSV Column Extractor</CardTitle><CardDescription className="mt-1 max-w-2xl">Select only the columns you need from CSV data, remove duplicates, sort records, and export a clean CSV.</CardDescription></div></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={sample}><FileText className="mr-1.5 h-3.5 w-3.5"/>Sample</Button><Button size="sm" variant="ghost" onClick={()=>{setInput("");setRows([]);setSelected([])}} disabled={!input&&!rows.length}><X className="mr-1.5 h-3.5 w-3.5"/>Clear</Button></div></div>
    {headers.length>0&&<Card className="border-border/60 bg-muted/10"><CardHeader className="pb-2"><CardTitle className="text-sm">Columns</CardTitle><CardDescription className="text-xs">By default all columns are included.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{headers.map((name)=><button key={name} type="button" onClick={()=>setSelected((current)=>{const base=current.length?current:headers;return base.includes(name)?base.filter(x=>x!==name):[...base,name];})} className={"rounded-md border px-2.5 py-1.5 text-xs "+(active.includes(name)?"border-primary/40 bg-primary/10":"border-border/60 text-muted-foreground")}>{name}</button>)}</CardContent></Card>}
    <Card className="border-border/60 shadow-none"><CardHeader className="pb-3"><CardTitle className="text-sm">CSV input</CardTitle><CardDescription className="text-xs">Parsing happens locally in the browser.</CardDescription></CardHeader><CardContent className="space-y-3"><Textarea value={input} onChange={(e)=>setInput(e.target.value)} rows={12} className="min-h-[250px] resize-y font-mono text-xs sm:text-sm" placeholder="name,email,role…" spellCheck={false}/><div className="flex flex-wrap gap-4 text-xs text-muted-foreground"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={dedupe} onChange={(e)=>setDedupe(e.target.checked)}/>Deduplicate rows</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={sort} onChange={(e)=>setSort(e.target.checked)}/>Sort rows</label></div><div className="flex justify-end"><Button onClick={extract} disabled={!input.trim()}><Filter className="mr-2 h-4 w-4"/>Extract columns</Button></div></CardContent></Card>
    {rows.length>0&&<Card className="overflow-hidden border-border/60"><CardHeader className="border-b border-border/50 py-3.5"><div className="flex flex-wrap items-center justify-between gap-2"><div><CardTitle className="text-sm">{rows.length} rows</CardTitle><CardDescription className="text-xs">Only the selected fields are included.</CardDescription></div><div className="flex gap-1.5"><Button size="sm" variant="outline" onClick={copy}><Copy className="mr-1.5 h-3.5 w-3.5"/>Copy</Button><Button size="sm" variant="outline" onClick={exportCsv}><Download className="mr-1.5 h-3.5 w-3.5"/>CSV</Button></div></div></CardHeader><CardContent className="p-0"><div className="max-h-[560px] overflow-auto divide-y divide-border/40">{rows.slice(0,1000).map((row,i)=><pre key={String(i)} className="m-0 whitespace-pre-wrap px-4 py-3 font-mono text-xs">{JSON.stringify(row,null,2)}</pre>)}</div></CardContent></Card>}
  </div>;
}
