"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const LAYOUTS = ["bottom-bar", "center-modal", "corner-box", "slide-in"];
const REGULATIONS = ["GDPR (EU)", "CCPA (California)", "Both"];

export default function ConsentManagementGenerator() {
  const [layout, setLayout] = useState("bottom-bar");
  const [regulation, setRegulation] = useState("Both");
  const [company, setCompany] = useState("Your Company");
  const [code, setCode] = useState("");

  const generate = () => {
    setCode(`<!-- Consent Management Banner — Generated by SopKit -->
<div id="sopkit-consent-banner" style="
  position: fixed;
  ${layout === "bottom-bar" ? "bottom: 0; left: 0; right: 0;" : ""}
  ${layout === "center-modal" ? "top: 50%; left: 50%; transform: translate(-50%, -50%); max-width: 500px;" : ""}
  ${layout === "corner-box" ? "bottom: 20px; right: 20px; max-width: 360px;" : ""}
  ${layout === "slide-in" ? "bottom: 0; left: 0; max-width: 400px;" : ""}
  z-index: 10000;
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 24px;
  box-shadow: 0 10px 40px rgba(0,0,0,0.15);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  display: none;
">
  <h3 style="margin: 0 0 8px; font-size: 16px; font-weight: 600; color: #1a1a2e;">Privacy Preferences</h3>
  <p style="margin: 0 0 16px; font-size: 13px; color: #64748b; line-height: 1.5;">
    We use cookies and similar technologies to enhance your experience. Select your preferences below.
  </p>
  <div style="margin-bottom: 16px;">
    <label style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px; font-size: 13px; cursor: pointer;">
      <input type="checkbox" checked disabled /> <strong>Essential</strong> (required)
    </label>
    <label style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px; font-size: 13px; cursor: pointer;">
      <input type="checkbox" id="sopkit-analytics" checked /> Analytics
    </label>
    <label style="display: flex; align-items: center; gap: 8px; font-size: 13px; cursor: pointer;">
      <input type="checkbox" id="sopkit-marketing" /> Marketing
    </label>
  </div>
  <div style="display: flex; gap: 8px; flex-wrap: wrap;">
    <button onclick="acceptConsent()" style="flex: 1; padding: 10px 16px; background: #1a1a2e; color: #fff; border: none; border-radius: 8px; font-size: 13px; font-weight: 500; cursor: pointer;">Accept All</button>
    <button onclick="saveConsent()" style="flex: 1; padding: 10px 16px; background: #f1f5f9; color: #1a1a2e; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 13px; cursor: pointer;">Save Preferences</button>
    <button onclick="document.getElementById('sopkit-consent-banner').style.display='none'" style="padding: 10px 16px; background: transparent; color: #64748b; border: none; font-size: 13px; cursor: pointer;">Decline All</button>
  </div>
</div>
<script>
  function acceptConsent() {
    localStorage.setItem('consent-preferences', JSON.stringify({ essential: true, analytics: true, marketing: true }));
    document.getElementById('sopkit-consent-banner').style.display = 'none';
  }
  function saveConsent() {
    localStorage.setItem('consent-preferences', JSON.stringify({
      essential: true,
      analytics: document.getElementById('sopkit-analytics').checked,
      marketing: document.getElementById('sopkit-marketing').checked
    }));
    document.getElementById('sopkit-consent-banner').style.display = 'none';
  }
  if (!localStorage.getItem('consent-preferences')) {
    document.getElementById('sopkit-consent-banner').style.display = 'block';
  }
</script>
<!-- Compliance: ${regulation} -->`);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Consent Management Generator</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="space-y-2">
          <label className="text-xs text-muted-foreground">Company Name</label>
          <input className="w-full border rounded px-2 py-1 text-sm" value={company} onChange={e => setCompany(e.target.value)} />
        </div>
        <div className="space-y-1">
          <label className="text-xs text-muted-foreground">Layout</label>
          <div className="flex gap-2 flex-wrap">
            {LAYOUTS.map(l => <button key={l} onClick={() => setLayout(l)} className={`px-3 py-1 text-xs rounded-full border ${layout === l ? "bg-primary text-primary-foreground" : ""}`}>{l.replace(/-/g, " ")}</button>)}
          </div>
        </div>
        <div className="space-y-1">
          <label className="text-xs text-muted-foreground">Regulation</label>
          <div className="flex gap-2 flex-wrap">
            {REGULATIONS.map(r => <button key={r} onClick={() => setRegulation(r)} className={`px-3 py-1 text-xs rounded-full border ${regulation === r ? "bg-primary text-primary-foreground" : ""}`}>{r}</button>)}
          </div>
        </div>
        <Button onClick={generate}>Generate Code</Button>
        {code && (
          <div className="space-y-2">
            <div className="p-3 border rounded bg-muted/50 text-xs font-mono whitespace-pre-wrap max-h-60 overflow-auto">{code}</div>
            <Button variant="outline" size="sm" onClick={() => navigator.clipboard.writeText(code)}>Copy</Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
